[theme]
# Matrix neon green
primaryColor = "lt-green"
# Black void BG
backgroundColor = "black"
# Dark matrix code BG
secondaryBackgroundColor = "lt-grey"
# Glowing text
textColor = "lt-green"
# MONO font (terminal code style)
font = "monospace"

# Wide layout for immersion
[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
